<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="hub" nsURI="urn:org.nasdanika.webtest.hub" nsPrefix="org.nasdanika.webtest.hub">
  <eClassifiers xsi:type="ecore:EClass" name="Hub" eSuperTypes="../../org.nasdanika.cdo.security/model/security.ecore#//LoginPasswordProtectionDomain #//ApplicationOwner #//BreadcrumbsProvider">
    <eAnnotations source="org.nasdanika.cdo.web:private"/>
    <eOperations name="testOperation" eType="#//Application">
      <eParameters name="prm" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Web Test Hub"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guest" eType="#//Guest"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="users" upperBound="-1"
        eType="#//User" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="administrators" eType="ecore:EClass ../../org.nasdanika.cdo.security/model/security.ecore#//Group"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="slideWidth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="800"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ApplicationOwner" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="applications" upperBound="-1"
        eType="#//Application" containment="true">
      <eAnnotations source="org.nasdanika.cdo.web:eager-obj"/>
      <eAnnotations source="org.nasdanika.cdo.web:lenient"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Guest" eSuperTypes="../../org.nasdanika.cdo.security/model/security.ecore#//User"/>
  <eClassifiers xsi:type="ecore:EClass" name="User" eSuperTypes="#//ApplicationOwner ../../org.nasdanika.cdo.security/model/security.ecore#//LoginPasswordHashUser"/>
  <eClassifiers xsi:type="ecore:EClass" name="Application" eSuperTypes="#//BreadcrumbsProvider">
    <eOperations name="getSummaryRowCells" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        eExceptions="#//Exception">
      <eAnnotations source="org.nasdanika.cdo.web:getter"/>
      <eParameters name="context" eType="#//HttpContext"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testSessions" upperBound="-1"
        eType="#//TestSession" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="securityToken" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="screenshots" upperBound="-1"
        eType="#//Screenshot" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="HttpContext" instanceClassName="org.nasdanika.web.HttpContext"/>
  <eClassifiers xsi:type="ecore:EClass" name="Descriptor" eSuperTypes="#//JSONLoader">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="description" eType="#//Description"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Description" eSuperTypes="#//JSONLoader">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="html" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestSession" eSuperTypes="#//Descriptor #//BreadcrumbsProvider">
    <eStructuralFeatures xsi:type="ecore:EReference" name="testResults" upperBound="-1"
        eType="#//TestResult" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pageResults" upperBound="-1"
        eType="#//PageResult" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actorResults" upperBound="-1"
        eType="#//ActorResult" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="published" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="progress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timestamp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="node" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OperationStatus">
    <eLiterals name="Pass"/>
    <eLiterals name="Fail" value="1"/>
    <eLiterals name="Error" value="2"/>
    <eLiterals name="Pending" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestResult" eSuperTypes="#//Descriptor #//BreadcrumbsProvider">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pageResults" upperBound="-1"
        eType="#//PageResult" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actorResults" upperBound="-1"
        eType="#//ActorResult" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestClassResult" eSuperTypes="#//TestResult">
    <eStructuralFeatures xsi:type="ecore:EReference" name="methodResults" upperBound="-1"
        eType="#//TestMethodResult" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stats" upperBound="-1"
        eType="#//StatsEntry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StatsEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestSuiteResult" eSuperTypes="#//TestResult">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//TestResult" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterizedTestResult" eSuperTypes="#//TestSuiteResult">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterDescriptors" upperBound="-1"
        eType="#//Descriptor" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Screenshot">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timestamp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contentType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="digest" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="beforeOperations" upperBound="-1"
        eType="#//OperationResult" eOpposite="#//OperationResult/beforeScreenshot"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="afterOperations" upperBound="-1"
        eType="#//OperationResult" eOpposite="#//OperationResult/afterScreenshot"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationResult" eSuperTypes="#//Descriptor #//BreadcrumbsProvider">
    <eStructuralFeatures xsi:type="ecore:EReference" name="screenshots" upperBound="-1"
        eType="#//Screenshot"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//OperationResult" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operationName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="arguments" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="beforeTiming" eType="ecore:EClass ../../org.nasdanika.webtest.performance/model/performance.ecore#//TimingBase"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="beforeScreenshot" eType="#//Screenshot"
        eOpposite="#//Screenshot/beforeOperations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="afterTiming" eType="ecore:EClass ../../org.nasdanika.webtest.performance/model/performance.ecore#//TimingBase"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="afterScreenshot" eType="#//Screenshot"
        eOpposite="#//Screenshot/afterOperations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="failure" eType="#//Throwable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="error" eType="#//Throwable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="start" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="finish" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//OperationStatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Throwable" eSuperTypes="#//JSONLoader">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stackTrace" upperBound="-1"
        eType="#//StackTraceEntry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StackTraceEntry" eSuperTypes="#//JSONLoader">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="className" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="methodName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="native" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InitializationResult" eSuperTypes="#//PageMethodResult"/>
  <eClassifiers xsi:type="ecore:EClass" name="MethodResult" eSuperTypes="#//OperationResult"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActorMethodResult" eSuperTypes="#//MethodResult">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actorResult" eType="#//ActorResult"
        eOpposite="#//ActorResult/results"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PageMethodResult" eSuperTypes="#//MethodResult">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pageResult" eType="#//PageResult"
        eOpposite="#//PageResult/results"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestMethodResult" eSuperTypes="#//OperationResult">
    <eOperations name="loadTiming" eType="ecore:EClass ../../org.nasdanika.webtest.performance/model/performance.ecore#//TimingBase"
        eExceptions="#//Exception">
      <eParameters name="json" eType="#//JSONObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameters" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="navigationTiming" upperBound="-1"
        eType="ecore:EClass ../../org.nasdanika.webtest.performance/model/performance.ecore#//NavigationTiming"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Coverage" eSuperTypes="#//Descriptor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="invocations" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActorResult" eSuperTypes="#//Descriptor #//BreadcrumbsProvider">
    <eStructuralFeatures xsi:type="ecore:EReference" name="results" upperBound="-1"
        eType="#//ActorMethodResult" eOpposite="#//ActorMethodResult/actorResult"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coverage" upperBound="-1"
        eType="#//Coverage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="proxy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PageResult" eSuperTypes="#//Descriptor #//BreadcrumbsProvider">
    <eStructuralFeatures xsi:type="ecore:EReference" name="results" upperBound="-1"
        eType="#//PageMethodResult" eOpposite="#//PageMethodResult/pageResult"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coverage" upperBound="-1"
        eType="#//Coverage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="webElements" upperBound="-1"
        eType="#//WebElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="proxy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WebElement" eSuperTypes="#//Descriptor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="locators" upperBound="-1"
        eType="#//Locator" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Locator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="how" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="using" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="JSONObject" instanceClassName="org.json.JSONObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="JSONLoader" instanceClassName="org.nasdanika.core.JSONLoader"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BreadcrumbsProvider" instanceClassName="org.nasdanika.webtest.hub.BreadcrumbsProvider"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Exception" instanceClassName="java.lang.Exception"/>
</ecore:EPackage>
